name: Update Publications (PubMed)

on:
  schedule:
    - cron: "17 5 * * *"  # every day at 05:17 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Build publications page
        run: python scripts/build_publications.py --config scripts/pubmed_config.json --output publications.html

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add publications.html
          git commit -m "chore: nightly PubMed sync [skip ci]" || echo "No changes to commit"
          git push
