name: Update Publications (PubMed)

on:
  schedule:
    # Runs every day at 09:10 UTC
    - cron: "10 9 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-inject:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (if any)
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Update publications.html from PubMed
        run: |
          set -euo pipefail
          if [ -f scripts/build_publications_patched.py ]; then
            PY=scripts/build_publications_patched.py
          else
            PY=scripts/build_publications.py
          fi

          if [ ! -f scripts/pubmed_config.json ]; then
            echo "ERROR: scripts/pubmed_config.json not found."
            exit 1
          fi

          if [ ! -f publications.html ]; then
            echo "ERROR: publications.html not found at repo root."
            exit 1
          fi

          python3 "$PY" --config scripts/pubmed_config.json --mode inject --target publications.html

      - name: Commit & push changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(pubmed): refresh publications.html from PubMed"
          file_pattern: "publications.html"
